apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy lpp + StorageClasses in one shot:
#   kubectl apply -k localdev/manifests/
resources:
  - 00-provisioner.yaml
  - 01-storageclasses.yaml
